#!/bin/bash
export HOME=/home/theia
export USER_ID=$(id -u)
export GROUP_ID=$(id -g)

if [ -w /etc/passwd ]; then
  echo "user:x:$(id -u):$(id -g):user user:${HOME}:/sbin/nologin" >> /etc/passwd
fi
exec "$@"
